### ISSUE TITLE
Baseline hyperparameters& datasets

### ISSUE THREAD

**Issue by XuhuiZhou** [skywalker023/pragmatic-consistency#1]
Hi! Could you specify what hyperparameters you use when finetuning the Blender model on PersonaChat? (I did not see that specified in your paper). To be more specific, what's the parlai comment you use to finetune the model? We tried the following commend but did not obtain the same results: 
```parlai train_model -m transformer/generator --delimiter ‘\n’ -t personachat:self_original -bs 4 -mf zoo:blender/blender_90M/model -tblog True -stim 1000 -lr 0.0001```

**Comment by XuhuiZhou** [comment]
I also tried the following command:
```python parlai/scripts/eval_model.py --task convai2:Self -mf zoo:blender/blender_90M/model -bs 32 --metrics hits@1 --rank-candidates true```
but failed to reproduce the results in the paper. Could you tell me the command you use?

**Comment by skywalker023** [comment]
Hello Xuhui! Thanks for your interest!
We used the Blender model as is without further finetuning.
The command for evaluating the Blender on convai2 is
`python eval_personachat.py --conscious-target self -t tasks.teachers:SelfConsciousDialogueTeacher --model agents.selfconscious_blender:SelfConsciousBlenderAgent --batchsize 48 --fp16 false`

Other evaluation commands can be found in the README! 😄

**Comment by XuhuiZhou** [comment]
Hi, thanks for the response
from what I understand, isn't the commend you show above is the Blender with the self-conscious mechanism? Can you show me the commend you use for the original Blender?

**Comment by skywalker023** [comment]
Oh, actually that's also in the README!

> In case you want to run the evaluation with vanilla Blender as is, set the `--conscious-target` to `none`.

So, if you want to run the original Blender on Convai2 the command should be like the following:
`python eval_personachat.py --conscious-target none -t tasks.teachers:SelfConsciousDialogueTeacher --model agents.selfconscious_blender:SelfConsciousBlenderAgent --batchsize 48 --fp16 false`

Is this the command you are looking for?

**Comment by XuhuiZhou** [comment]
Cool, that's exactly what I am looking for!

**Comment by skywalker023** [comment]
Great! Open the issue when anything comes up!

**Comment by XuhuiZhou** [comment]
Hi, 
Just one more question. In your experiments, did you use the original or the revised version of PersonaChat?
