### ISSUE TITLE
Experiment datasets

### ISSUE THREAD

**Issue by XuhuiZhou** [skywalker023/pragmatic-consistency#2]
Hi,
One more question. In your experiments, did you use the original or the revised version of PersonaChat? Or both? (I see a both setting in Parlai's doc but not sure what that implies)

**Comment by skywalker023** [comment]
Oh, we used the 'convai2' version, which is a competition version of PersonaChat!
[https://github.com/facebookresearch/ParlAI/tree/master/parlai/tasks/convai2](https://github.com/facebookresearch/ParlAI/tree/master/parlai/tasks/convai2)
