### ISSUE TITLE
How to interact with the model?

### ISSUE THREAD

**Issue by SkyAndCloud** [skywalker023/pragmatic-consistency#3]
Hello, thank you for the great work. I wander how to interact with the provided checkpoint via CLI? Could you provide a script to do it?

**Comment by mdda** [comment]
I had the same question, but a quick look at the code shows that these models are integrated with [parlai](https://parl.ai/) - so it should be simple enough to check up on how that framework can be interrogated via the terminal (or other UIs that they have already integrated).  A good place to start might be : https://github.com/facebookresearch/ParlAI/tree/main/parlai/chat_service/services/terminal_chat

**Comment by skywalker023** [comment]
Hello, thanks for opening the issue!
Currently, I have no bandwidth to update the codes for this project 😢
However, as @mdda mentioned, our code follows the parlai convention. 
So hopefully, you will be able to use the parlai features accordingly!
I do want to mention that you should use the up-to-date parlai to have access to the new features.
