### ISSUE TITLE
[C-score 관련]

### ISSUE THREAD

**Issue by passing2961** [skywalker023/pragmatic-consistency#4]
안녕하세요

Blender 90M 모델에 대해 정량적 실험 결과가 논문에 기재된 결과와 유사하게 잘 복원되는지를 확인하는 도중에 한 가지 질문이 생겼습니다.

논문에 기재된 0.85 (Blender S0 에 해당) C-score 와 달리, 제가 직접 실행해보니 C-score 가 음수 값이 산출되고 있습니다. 실험에 사용한 데이터셋은 `convai2:normalized` valid dataset 에 대해 정량적 점수를 구하고 있습니다. (다른 ppl, f1 값은 유사하게 산출되고 있습니다) 모델은 동일하게 `zoo:blender/blender_90M/model` 을 사용하고 있습니다.

혹시, 제가 놓친 부분이 있거나 잘못한 부분이 있을까요?

감사합니다.

**Comment by skywalker023** [comment]
안녕하세요?
논문에 관심가져주셔서 감사합니다!
아마 사용하신 데이터셋이 normalized version이라는 점에서 비롯한 차이가 아닐까 싶습니다
저는 convai2 original 데이터를 사용했습니다.
혹시 그래도 결과가 다르게 나온다면 알려주세요!

**Comment by passing2961** [comment]
안녕하세요!

다른 버전으로도 했을 때 동일한 결과가 나오고 있습니다. 그래서, 해당 repo 를 clone 뜬 다음에 결과가 그대로 복원되는지를 확인하고 있습니다. 따라서, conda 를 통해 환경까지 구축하였는데, dnli_bert.bin 파일이 load 되고 있지 않습니다. 에러는 아래와 같으며, 예상되는 이유로는 google drive download 될 때 파일이 끝까지 다운로드되고 있지 않은거 같다는 생각이 듭니다.

```
_pickle.UnpicklingError: invalid load key, '<'.
```

감사합니다.

**Comment by passing2961** [comment]
안녕하세요!

`dnli_model.bin` 모델이 잘 다운로드 하니 정상적으로 c score 가 잘 나옵니다.
한 가지 궁금한 점은, 논문에서 보고되는 정량적 실험 결과는 convai2 데이터셋의 validation set 에 대해서 성능을 본 것인가요? 왜냐하면, convai2 test set 이 제공되지 않고 있는데 혹시나 personachat 의 test set 에 대해서 평가를 한 것인지 궁금해서 여쭤봅니다.

감사합니다.

**Comment by skywalker023** [comment]
안녕하세요!
정상적으로 나온다니 다행입니다!
네 맞습니다 논문에 나와있듯이 convai2 valid set에 했습니다!
감사합니다
